on:
  push:
    branches:
      - main
    paths-ignore:
      - '**/*.md'
      - '.github/CODEOWNERS'
      - 'catalog-info.yaml'
      - 'mkdocks.yaml'
  # pull_request:
  #   branches:
  #     - '*'
    # paths-ignore:
    #   - '**/*.md'
    #   - '.github/CODEOWNERS'
    #   - 'catalog-info.yaml'
    #   - 'mkdocks.yaml'
  workflow_dispatch:

name: CI

jobs:
  release-branch:
    name: Create Release Branch
    runs-on: [ubuntu-latest]
    permissions:
      pull-requests: write
      contents: write
    if: github.event_name == 'push' || github.event_name == 'workflow_dispatch'
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          cache: npm
          node-version-file: .nvmrc
          registry-url: https://npm.pkg.github.com/

      - name: Install Dependencies
        run: npm ci
        
      - name: Create Release Pull Request
        uses: changesets/action@v1
        with:
          commit: 'publish 🚀'
          title: 'Next Release 🚀'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}