name: Release Packages

on:
  pull_request:
    types: [closed]
  workflow_dispatch:

jobs:
  release-packages:
    # if: ${{ github.event.pull_request.merged == true && endsWith(github.head_ref, 'changeset-release/main') }}
    name: Release Packages
    runs-on: [ubuntu-latest]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          cache: npm
          node-version-file: .nvmrc
          registry-url: https://npm.pkg.github.com/
      - name: Install Dependencies
        run: npm ci
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Release Packages
        run: npm run publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}