on:
  workflow_dispatch:

name: Test

jobs:
  release-branch:
    name: Create Release Branch
    runs-on: [ubuntu-latest]
    steps:
      - name: Write the cypress.env.json file
        run: echo '${{ secrets.CYPRESS_ENV_CI  }}' | base64 --decode > cypress.env.json
        shell: bash
      - name: Echo json
        run: cat cypress.env.json
        shell: bash
